"""Aggregate manually verified LLM evaluation cases without inventing metrics.

The default mode is intentionally strict: every row must be manually reviewed.
Rows generated by run_llm_evaluation_cases.py start with manual_reviewed=false
and are rejected until a human reviewer updates them.

Required human fields per row:
- manual_reviewed: true
- manual_unsupported_claim: boolean
- human_corrected: boolean
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from statistics import mean


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", default="artifacts/evaluation/llm_metrics.json")
    args = parser.parse_args()

    rows = [
        json.loads(line)
        for line in Path(args.input).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if not rows:
        raise SystemExit("Evaluation set is empty")

    unreviewed = [
        row.get("case_id", "<unknown>")
        for row in rows
        if row.get("manual_reviewed") is not True
        or not isinstance(row.get("manual_unsupported_claim"), bool)
        or not isinstance(row.get("human_corrected"), bool)
    ]
    if unreviewed:
        raise SystemExit(
            "Final LLM metrics require manual review. Incomplete cases: "
            + ", ".join(unreviewed)
        )

    action_agreement = []
    policy_correct = []
    manual_unsupported = []
    guard_flags = []
    corrected = []
    latencies = []
    tool_coverage = []

    for row in rows:
        review = row["actual_review"]
        action_agreement.append(review.get("recommended_action") == row.get("expected_action"))

        expected_policy = row.get("expected_policy_id")
        actual_policy = (review.get("policy_reference") or {}).get("policy_id")
        if expected_policy is not None:
            policy_correct.append(actual_policy == expected_policy)

        manual_flag = bool(row["manual_unsupported_claim"])
        guard_flag = bool(review.get("unsupported_claims_detected", False))
        manual_unsupported.append(manual_flag)
        guard_flags.append(guard_flag)
        corrected.append(bool(row["human_corrected"]))
        if row.get("latency_ms") is not None:
            latencies.append(float(row["latency_ms"]))

        calls = set(row.get("tool_calls") or [])
        tool_coverage.append(
            {"get_case_context", "get_visual_evidence", "get_return_policy"}.issubset(calls)
        )

    true_unsupported = sum(manual_unsupported)
    caught_unsupported = sum(m and g for m, g in zip(manual_unsupported, guard_flags))

    payload = {
        "llm_review": {
            "evaluation_cases": len(rows),
            "review_action_agreement": sum(action_agreement) / len(action_agreement),
            "policy_correctness": (sum(policy_correct) / len(policy_correct)) if policy_correct else None,
            "manual_unsupported_claim_rate": sum(manual_unsupported) / len(manual_unsupported),
            "grounding_guard_recall_on_unsupported": (
                caught_unsupported / true_unsupported
            ) if true_unsupported else None,
            "human_correction_rate": sum(corrected) / len(corrected),
            "required_tool_coverage": sum(tool_coverage) / len(tool_coverage),
            "average_latency_ms": mean(latencies) if latencies else None,
        },
        "provenance": (
            "Aggregated only after every fixed Gemini evaluation row was manually reviewed."
        ),
    }

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
